### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [DrewThomasson/VoxNovel#1]
Hi,
Thank you for making this awesome program. Would you mind adding a license (ie Unlicense, MIT, ISC)?
Thank you!

**Comment by DrewThomasson** [comment]
I mean sure if I can I forgot about the license part I just wanted to make a cool free program, but like would I even be able to considering it uses Calibre, BOOKNLP and Coqui TTS?

**Comment by DrewThomasson** [comment]
Added MIT License!

**Comment by fakerybakery** [comment]
Thanks!
