### ISSUE TITLE
Run on Colab Google

### ISSUE THREAD

**Issue by sitariom** [DrewThomasson/VoxNovel#11]
Is it possible to run it on a colab's notebook?

great project!

**Comment by DrewThomasson** [comment]
Unfortunately no, not at this time, 

GOOGLE COLAB has a idle timeout at  90 minutes 

While a full sizable audiobook usually takes around slightly faster than real time AUDIO generation on a good GPU (My use is a 12gb VRAM 3060 Nvidia GFORCE RTX)


This makes it very challenging to implement and less worthwhile, 

when you could just grab an older laptop or desktop to have it run on CPU for like 48 hours.

**Comment by DrewThomasson** [comment]
Surprisingly, 

I used to have a colab version in older versions of VoxNovel, 

but like I said.... the google colab idle timeout makes it really hard to justify. 

:/

**Comment by DrewThomasson** [comment]
Reopening issue because I'm working on a headless version of voxnovel


https://github.com/DrewThomasson/VoxNovel/issues/13#issuecomment-2093569823

**Comment by DrewThomasson** [comment]
> Is it possible to run it on a colab's notebook?
> 
> great project!

## I now have a working headless google colab that's working added to the readme at: 
## 🤖 Headless VoxNovel Google Colab

Explore and run the interactive version of the Headless VoxNovel project directly on Google Colab! Get started [here](https://colab.research.google.com/drive/15pp2hFBo2fD3legDQfWY5DMt-aI-HKKF?usp=sharing).
