### ISSUE TITLE
ability to use this project on a headless system

### ISSUE THREAD

**Issue by danielw97** [DrewThomasson/VoxNovel#13]
Hi there,
I've just started looking at this project, and it looks great at first glance.
Thanks a lot for all of the work you've put in so far!
As someone who primarily works on cli-based (no graphical user interface) systems, it would be great to have a version of this project that's able to be ran strictly from the command line.
Is there any possibility either now or in future to either be able to pass flags to the program from the cli, or be able to use a web interface or similar to change the book selection and used voices?
I completely understand if not, although figured I would at least suggest this idea.
Thanks in advance.

**Comment by DrewThomasson** [comment]
Thanks for the feedback and suggestion!

Sadly that would probably take a lot of work in remaking the program, 

I'm just a single developer with only so much free time.

I'd probably need help with anyone who has any experience in building command line interface applications.



The closest thing I've done was when I made a autorun version of this program that ran through only terminal, but that's been put on hold at the moment. 

:/

**Comment by DrewThomasson** [comment]
Update:

I'm currently creating a headless version of Voxnovel.

This should also allow a easier implementation with docker and google colab.

🎉🥳

**Comment by DrewThomasson** [comment]
ITS COMPLETE 🎉🎉🥳

A headless variant is now available under the file name 

headless_voxnovel.py
