### ISSUE TITLE
Error importing voice model 

### ISSUE THREAD

**Issue by kirkfall** [DrewThomasson/VoxNovel#14]
I am using WLS Ubuntu on windows

Selected TTS model: tts_models/multilingual/multi-dataset/xtts_v1.1
Selected TTS model: tts_models/multilingual/multi-dataset/xtts_v2
Updated voice for 2493:NATO.?: daniel.M
Updated voice for Narrator: daniel.M
Language for Narrator changed to en
Updated voice for Narrator: daniel.M
Added voice actor data to Working_files/Book/book.csv
Added language data to the CSV file.
Voice actor: daniel.M, en
found fine tuned for voice actor: daniel.M: loading custom model...
Exception in thread Thread-1 (generate_audio):
Traceback (most recent call last):
  File "/home/unix/miniconda3/envs/VoxNovel/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/unix/miniconda3/envs/VoxNovel/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/unix/VoxNovel/2GPU_Audio_generation.py", line 1916, in generate_audio
    fineTune_audio_generate(text=fragment, file_path=f"Working_files/temp/{temp_count}.wav", speaker_wav=speaker_wavz[0], language=language_code, voice_actor=voice_actor)
  File "/home/unix/VoxNovel/2GPU_Audio_generation.py", line 1746, in fineTune_audio_generate
    config.load_json(CONFIG_PATH)
  File "/home/unix/miniconda3/envs/VoxNovel/lib/python3.10/site-packages/coqpit/coqpit.py", line 726, in load_json
    with open(file_name, "r", encoding="utf8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tortoise/voices/daniel.M/model/config.json'
CSV Index: 0
audio_0_0
Playing Working_files/generated_audio_clips/audio_0_0.wav
Could not play the audio file: No file 'Working_files/generated_audio_clips/audio_0_0.wav' found in working directory '/home/unix/VoxNovel'.
CSV Index: 1
audio_1_0
Playing Working_files/generated_audio_clips/audio_1_0.wav
Could not play the audio file: No file 'Working_files/generated_audio_clips/audio_1_0.wav' found in working directory '/home/unix/VoxNovel'.

/home/unix/miniconda3/envs/VoxNovel/cd /home/unix/miniconda3/envs/VoxNovel/

**Comment by DrewThomasson** [comment]
Sorry about the late responses I'll look into this, hm

**Comment by DrewThomasson** [comment]
Did it work?, should I close this issue?
