### ISSUE TITLE
gui_run.py finish with killed message

### ISSUE THREAD

**Issue by Ogurash-dev** [DrewThomasson/VoxNovel#20]
Hi, 
I have that in my WSL when i launch gui_run.py: 
```
[nltk_data]   Package punkt is already up-to-date!
--- spacy: 79.679 seconds ---
--- entities: 1502.808 seconds ---
--- quotes: 0.618 seconds ---
--- attribution: 0.027 seconds ---
--- name coref: 0.766 seconds ---
Killed
```
[log_wsl.txt](https://github.com/DrewThomasson/VoxNovel/files/15461767/log_wsl.txt)

Can you guide me for repair ?

**Comment by DrewThomasson** [comment]
Thanks for the log very helpful!

Anyway, looks like your probably running out of cpu ram,


So I guess the main questions are,

-How much ram does your computer have?

-How much ram free do you have when your running this

-how big of a book are you running through the program,

**Comment by Ogurash-dev** [comment]
Hello,

Thanks for for your quick feedback. You have found the source of the problem, I have 16 GB of RAM on my computer, but there is 8 GB free at launch.

My ebook is 536KO.

I have use the **Easy Windows 11 install** in your readme for the install.

For completion, i will gie you my dxdiag file if it can help.
[DxDiag.txt](https://github.com/DrewThomasson/VoxNovel/files/15464466/DxDiag.txt)

I expect that there any other issue but to add a new RAM bar?

Thanks a lot :)

**Comment by DrewThomasson** [comment]
Nice! 

Yeah you should be fine as long as you have enough ram,

So I guess it's solved lol.

**Comment by Ogurash-dev** [comment]
Thanks a lot, and i will add some RAM, do you think 32Go will be enough ? Or will i need 64Go?

**Comment by DrewThomasson** [comment]
16 should be enough anyway 32 is more than enough lol,

If you wanna test it beforehand before you upgrade you can try running it in the free google colab here as well,

https://colab.research.google.com/drive/15pp2hFBo2fD3legDQfWY5DMt-aI-HKKF?usp=sharing

**Comment by Ogurash-dev** [comment]
I will try with upgarde my VRAM on Windows 11, if that can't help i will try on Google Collab, but i m a newcomer on it...

I will send you the epub file so, when i Come back

**Comment by Ogurash-dev** [comment]
There is the epub file : https://drive.google.com/file/d/1CYR-Y_QlDY6JT_RYNSr7xSjSnrbFQUsQ/view?usp=sharing

I will try with another epub file later, because aftercheck, i don't exceed 12Go of used RAM

**Comment by DrewThomasson** [comment]
lol you GOTA allow access with the link

**Comment by Ogurash-dev** [comment]
Yes, sorry can you retry the access ask?

I have tested with Collad, that work where in WSL that crash, but due to exceed 12hours in the 3rd step, collab close the session.

**Comment by DrewThomasson** [comment]
Well as long as it started generating the audiobook and finished processing the book in colab then that's good lol

-just requested access again to the file
