### ISSUE TITLE
Trying to run on Ubuntu 24.04 Error when processing a chapter from my book.

### ISSUE THREAD

**Issue by bmcgonag** [DrewThomasson/VoxNovel#29]
I can run the application from the desktop, or by directly calling the script.  It tries to load the chapter I created, but crashes just as it finishes reading the chapter with the error:

```
Traceback (most recent call last):
  File "/home/brian/VoxNovel/gui_run.py", line 1706, in <module>
    from styletts2 import tts as stts
ModuleNotFoundError: No module named 'styletts2'

```

I re-ran `pip3 install styletts2`, and tried again, but it still crashed. 

I was using an .odt format, and saw this error:

```
Traceback (most recent call last):
  File "/usr/bin/ebook-convert", line 21, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 379, in main
    parser, plumber = create_option_parser(args, log)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/conversion/cli.py", line 332, in create_option_parser
    plumber = Plumber(input, output, log, reporter)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/calibre/calibre/ebooks/conversion/plumber.py", line 723, in __init__
    raise ValueError('Input file must have an extension')
ValueError: Input file must have an extension
Success, File processed successfully!

```
I saved the chapter as a .txt file, and still got the above error.

Not sure what's happening. The install appeared to go fine, but maybe it missed something?

**Comment by DrewThomasson** [comment]
'pip install styletts2'

**Comment by DrewThomasson** [comment]
Weird the single reinstall run command should of installed it 🤔 for you

**Comment by DrewThomasson** [comment]
How did you install it? The auto install single command?

**Comment by DrewThomasson** [comment]
And you're activating the VoxNovel conda env before running it right?

**Comment by bmcgonag** [comment]
So, yes, used the one liner command for install. Did the pip3 install styletts2, so how do I activate the conda?

**Comment by DrewThomasson** [comment]
Sorry about the late response,

Ohhh
Ok I think I know

Type in 

conda activate VoxNovel

And then

python --version 

Should now be 3.10




But also you should just be able to click the VoxNovel desktop shortcut to run it if you ran the single install command on Ubuntu.


Should be in your apps list with all the other apps 🤔

**Comment by bmcgonag** [comment]
I tried it but got dependency errors, so I just reran the installer, and now it seems to be working. Testing a chapter now.

**Comment by DrewThomasson** [comment]
nice, I await your final result

:)

**Comment by bmcgonag** [comment]
It worked.  I had asked a previous question about how to change the reader for various parts.  Do I just need to backspace the incorrectly chosen name, and type in the right one?  If I hit Load Block, it replaces anything I change.

**Comment by DrewThomasson** [comment]
WOOT!

backspace? 

if your using the gui one "gui_run.py" then you should just have dropdown for the voices available.....

**Comment by bmcgonag** [comment]
Yes, I do for the voices, but what I mean is in the lower space where it shows who is reading which sections.  In some cases it misidentifies the proper reader / voice to use.

**Comment by DrewThomasson** [comment]
....You may have to show me a video with what you're talking about, I want to make sure I 100% know what your talking about

I'll try making a video on explaining all the interworking of the GUI to send you and add to the readme in the meantime.

**Comment by bmcgonag** [comment]
Let me start with a couple of images.  
![Wrong_Voice_2](https://github.com/user-attachments/assets/ab76e870-90dd-4eb8-9c94-97f50c10a9d8)
![Wrong_Voice_1](https://github.com/user-attachments/assets/5dd5da7a-101d-43cd-a96d-80533fd17fd8)

Those show that the wrong voice has been set for that part. I'm wondering how I change the reader for those parts.  in the image Wrong_Voice_1, it attributes the text to character Dave, but it should be the Narrator. In Wrong_Voice_2 it attributes the text to character 'Man', but should be Leo.  Just not sure how to make it read the parts as the proper character.

**Comment by DrewThomasson** [comment]
Ok so getting this straight, 

You're not talking about how to change the voice for a character id right?
 Like for instance: If you wanted to change what voice actor is used for every line with the the character id of  "5:Dave.M:" 

Same thing for if for instance you wanted "5:Dave.M" and "Narrator:" to use the same voice actor because they are actually the same character in all cases but accidentally identified as two separate character IDs

## No Your actually talking about this case?

**NO**, Your talking about the specific case where there's a few lines you want to change the character ID for those lines because those few lines have the wrong character ID

Like in your case the character ID "5:Dave.M" might be a real character thats not the narrator, but at the beginning of your book its identifying some "Narrator:" lines as being "5:Dave.M" right?

**Comment by DrewThomasson** [comment]
So are you looking at changing the voice actor for every line with a specific character ID?

## OR

Are you looking at changing the **Character ID or Voice actor** for a **specific set** of lines in the book that have been mis-identfied?

**Comment by bmcgonag** [comment]
The 2nd one.  I'm looking at re-identifying the character or Voice actor for specific lines / sets of lines in the book.

**Comment by DrewThomasson** [comment]
I actually was planning on adding this functionality in the final Beta gui thing, 

You know that weird third window that shows up at the end.

I'll see if I can find any time to finalize it.


## In the mean time (if your fine with manually editing the csv spreadsheet files)

first make sure the first book processing step has been done, then

I suppose you could go into the quotes.csv and the non_quotes.csv file and manually modify the values for the column "Speaker" for the rows you want to change to the correct speaker?

Then exit the program and just launch the program again skipping the booknlp step or it'll regenerate those files.


that might work

## the files are located at VoxNovell/Working_files/Book

**Comment by DrewThomasson** [comment]
## FIXED

Added a new gui window to allow one to manually change the speakers for specific lines before it's passed to the tts gui setup stage.

This should fix this kind of issue on your end :)

## FIX

Just do a git pull in the VoxNovel folder

if your in windows you'll have to go into the 

`wsl -d Ubuntu` 

environment to run that command

It should update your code to the latest version :)

**Comment by DrewThomasson** [comment]
Hope you like the custom addition to the GUI :)

**Comment by DrewThomasson** [comment]
Hit me up if you have any other issues

**Comment by bmcgonag** [comment]
This worked great!  Thank you so much for all the help!
