### ISSUE TITLE
Error using new voice with Fine Tuned XTTS model

### ISSUE THREAD

**Issue by ScratchMode** [DrewThomasson/VoxNovel#32]
I've Imported this [Clone](https://drive.google.com/file/d/16IcvVOmtIQbRFAWnWbFSo_1Ef1MHUjoo/view?usp=sharing) a Voice Sample, and this [Model ](https://drive.google.com/file/d/1QDknmX0tvdw9FClspRiP31h8HMV75MSN/view?usp=sharing) and then when trying to generate audio immediately stalled out with the following error.

Using XTTS V2.0.2 Model Fine Tuned with this bastard of a git [project
](https://github.com/daswer123/xtts-finetune-webui)
> Added voice actor data to Working_files/Book/book.csv
> Added language data to the CSV file.
> Voice actor: Jay Snyder.M, en
> found fine tuned for voice actor: Jay Snyder.M: loading custom model...
> /home/voxnovel/miniconda/envs/VoxNovel/lib/python3.10/site-packages/TTS/utils/io.py:54: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   return torch.load(f, map_location=map_location, **kwargs)
> Computing speaker latents...
> Inference...
> Exception in thread Thread-3 (generate_audio):
> Traceback (most recent call last):
>   File "/home/voxnovel/miniconda/envs/VoxNovel/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/home/voxnovel/miniconda/envs/VoxNovel/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/voxnovel/VoxNovel/gui_run.py", line 1914, in generate_audio
>     fineTune_audio_generate(text=fragment, file_path=f"Working_files/temp/{temp_count}.wav", speaker_wav=speaker_wavz[0], language=language_code, voice_actor=voice_actor)
>   File "/home/voxnovel/VoxNovel/gui_run.py", line 1762, in fineTune_audio_generate
>     out = tts.inference(
>   File "/home/voxnovel/miniconda/envs/VoxNovel/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
>     return func(*args, **kwargs)
>   File "/home/voxnovel/miniconda/envs/VoxNovel/lib/python3.10/site-packages/TTS/tts/models/xtts.py", line 532, in inference
>     text_tokens = torch.IntTensor(self.tokenizer.encode(sent, lang=language)).unsqueeze(0).to(self.device)
>   File "/home/voxnovel/miniconda/envs/VoxNovel/lib/python3.10/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 653, in encode
>     return self.tokenizer.encode(txt).ids
> AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by DrewThomasson** [comment]
It might be that for my import your suppose to be importing the folder containing all the files, and for some reason I had to 
make the vocab file have a _ after it like "vocab.json_" instead of  "vocab.json"

###  Confirmed on my end I get the same error if I incorrectly rename the "vocab.json" file to "vocab.json_"

## FIX:

- If the custom model vocab file In the model dir is named "vocab.json" currently, then rename it "vocab.json_"
- OR if the customer model vocab file in the model dir is named "vocab.json_" currently, then rename it "vocab.json"

That should fix your issue. :)



--------------


## Ignore this  below lol this is extra just in case, Your issue is MOST LIKELY the thing above. :)

## If not
Try using my docker image to fine tune a model locally (If you have a Nvidia graphics card):
https://hub.docker.com/repository/docker/athomasson2/fine_tune_xtts/general

If you don't have nvida graphics card you could just my google colab image tho:
https://colab.research.google.com/drive/1sqQqzupo2pdjgggkrbM60sU6sBFYo3su?usp=sharing

**Comment by DrewThomasson** [comment]
Hit me up if you run into any other issues! :)

**Comment by DrewThomasson** [comment]
## Confirmed to fix the issue on my end!

As you can see here All I did was modify the name of the vocab.json file from "vocab.json" to "vocab.json_" and now it works :)

In fact here's your model back with that change (temp link-will auto-destruct once downloaded once)
https://file.io/prtxa7X9bBg0

along with a sample generated with that model and voice to prove it worked
[Example_Generated_audio_audio_0_0.wav.zip](https://github.com/user-attachments/files/16955162/Example_Generated_audio_audio_0_0.wav.zip)

**Comment by DrewThomasson** [comment]
# BETTER UPDATE!!

### I Just updated VoxNovel's gui_run.py code to automatically rename your vocab file for you when it sees it incorrectly named.


## So you Just go a git pull and you should be good to go :)

**Comment by ScratchMode** [comment]
Thanks again Drew, seems to working good again.
