### ISSUE TITLE
VoxNovel fails after not being able to resolve quotations

### ISSUE THREAD

**Issue by jdclark73** [DrewThomasson/VoxNovel#38]
As the title says, VoxNovel gets "Killed" after encountering "Cannot resolve quotation." I've attached a sample DRM free book (from Gutenberg), as well as the Working_files folder. It generates the CSV and everything. The book is just a nonfiction book and doesn't have any quotations, and the CSV lists the speakers all as Narrator. 

The book is in English, which is listed in the metadata when checking in Calibre beforehand, but on import into VoxNovel it says "No language detected" although from what I can tell in the script, a default language of "en" will be assigned anyway. 

Running on Windows through WSL. 

Also worth mentioning is that running "python gui_run.py" or "python headless_voxnovel.py" the only option is to load a file, which then immediately starts the processing (which fails in the end), but there are no further GUI options to change speakers, etc. Not sure how to activate the Coqui TTS GUI, for example. 

[VoxNovel epub files.zip](https://github.com/user-attachments/files/17250327/VoxNovel.epub.files.zip)

**Comment by DrewThomasson** [comment]
so..I looked at the book you gave it.....why are you giving it the "On the Origin of Species By Mea - Charles Darwin, cause This repo for like story books like harry potter or whatnot with multiple speakers

- That book appears to only have one speaker

- Have you tried giving it an actual story book with multiple speakers, idk harry potter?

- For books with single speakers I would suggest a different repo not made for literal story books, such as my other repo lol [ebook2audiobookxtts](https://github.com/DrewThomasson/ebook2audiobookXTTS)

**Comment by jdclark73** [comment]
I tried [ebook2audiobookXTTS](https://github.com/DrewThomasson/ebook2audiobookXTTS), and eventually got it running in Docker, was able to launch it and start a conversion, but after about 10 minutes it errored out, and the logs showed nothing. The terminal readout just stopped. It seemed like the connection on Docker just timed out, so I don't know if I need to go dig around in settings to solve that. Haven't used Docker or Gradio before so I don't know enough about them to know where it's breaking.

**Comment by DrewThomasson** [comment]
hm did it just like die in the middle of generating with xtts?

- if thats the case you might just need to increase the max allowed ram for docker idk, It should be able to run on 4gb tho

**Comment by jdclark73** [comment]
For the issue on VoxNovel, if you have time, it might be worth considering allowing single narrator conversion, with maybe some kind of error handling such as, "It looks like there is only one narrator in this book. VoxNovel is built for multiple voice parts. Would you still like to proceed with the conversion?" 

For the Docker issue, I'll open an issue in /ebook2audiobookXTTS. The terminal just stops, no errors or anything. You see the successful output plugging away, it produces multiple .wav files successfully if you check files in Docker, terminal keeps showing the fragments that are being made, and then you notice after a while that no new fragments are being produced. And eventually the terminal just goes back to the regular starting output ("PS C:\Users\username>" ). Then gradio says "Error" with no other info. And if you try to open localhost:7860 in another tab it says "Connection refused." I managed to convert a small test excerpt, with 5 minutes of audio. But if the process takes more than 30 minutes to run, then this connection issues seems to happen. 

The wrinkle is that it works perfectly fine on another computer I tried, also Windows 11. Firewall is set to allow docker in both, and I also set the computer to not go to sleep. I did a fresh install of Docker to see if that helped, but still no luck.
